const industryOptions = [
  "Automotive",
  "Aviation & Aerospace",
  "Banking & Finance",
  "Consumer Electronics",
  "e-commerce",
  "Education",
  "Energy & Oil",
  "Food & Beverage",
  "Government & Administration",
  "Hospitality & Events",
  "Hospitals & Healthcare",
  "Legal Services",
  "Logistics & Supply Chain",
  "Management & Consulting",
  "Marketing & Advertising",
  "Media",
  "Music",
  "Non-Profit",
  "Pharmaceuticals & Biotech",
  "Property",
  "Retail",
  "Sports",
  "Technology",
  "Transportation",
  "Travel & Leisure",
  "Other (Please Specify) ",
];

export { industryOptions };
